org: artemsopa
app: aws-image-uploader
service: aws-image-uploader
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}

functions:
  signIn:
    handler: ./src/index.signIn
    events:
      - http:
          path: /auth/sign-in
          method: post
  signUp:
    handler: ./src/index.signUp
    events:
      - http:
          path: /auth/sign-up
          method: post
  getAllImages:
    handler: ./src/index.getAllImages
    events:
      - http:
          path: /bucket
          method: get
  uploadImage:
    handler: ./src/index.uploadImage
    events:
      - http:
          path: /bucket
          method: post
  deleteImage:
    handler: ./src/index.deleteImage
    events:
      - http:
          path: /bucket
          method: delete