org: artemsopa
app: aws-sqs-redistribution
service: aws-sqs-redistribution
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    QUEUE_NAME: ${self:custom.queueName}
    ACCOUNT_ID: ${env:ACCOUNT_ID}
    REGION: ${self:provider.region}
    DB_HOST: ${env:RDS_DB_HOST}
    DB_PORT: ${env:RDS_DB_PORT}
    DB_USER: ${env:RDS_DB_USER}
    DB_PASSWORD: ${env:RDS_DB_PASSWORD}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: "arn:aws:sqs:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:${self:custom.queueName}"
    - Effect: "Allow"
      Action:
        - "sqs:ListQueues"
      Resource: "arn:aws:sqs:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:*"
    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource:
        - "*"

custom:
  queueName: aws-sqs-redistribution-${self:provider.stage}

functions:
  sender:
    handler: ./src/handler.sender
    events:
      - http:
          path: v1/sender
          method: post
          cors: true
  receiver:
    handler: ./src/handler.receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
    vpc:
      securityGroupIds:
        - sg-0fe96f314854bde70
      subnetIds:
        - subnet-0f9af9f93b661a6ad
        - subnet-0315b540cb1a0f6a0
        - subnet-0f877550548ce2fa1

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.queueName}
